/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_api_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Login */
        post: operations["auth_cookie_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Logout */
        post: operations["auth_cookie_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_api_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_api_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_api_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        /** Create Character */
        post: operations["create_character_api_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Character */
        get: operations["read_character_api_characters__character_id__get"];
        put?: never;
        post?: never;
        /** Delete Character */
        delete: operations["delete_character_api_characters__character_id__delete"];
        options?: never;
        head?: never;
        /** Update Character */
        patch: operations["update_character_api_characters__character_id__patch"];
        trace?: never;
    };
    "/api/characters/{character_id}/portrait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Portrait
         * @description A character with no portrait is a 404, exactly as another user's character is.
         *
         *     The list card only asks for this URL when the summary said there was something at it, so the
         *     404 is the unusual path and not a routine miss. It is cached for a day and hard to serve
         *     stale: the card hangs ``portrait_updated_at`` on the URL, so a replacement is a different URL.
         *     ``private``, because it is one user's image and there is a shared proxy in front of this.
         */
        get: operations["read_portrait_api_characters__character_id__portrait_get"];
        /**
         * Replace Portrait
         * @description The image as the raw request body, its type named by ``Content-Type``.
         *
         *     Deliberately not multipart: the request carries one file and no fields, so a part boundary
         *     would be ceremony around a body that is already exactly the bytes to store — and it would make
         *     ``python-multipart``, presently a transitive dependency of ``fastapi-users``, a direct one.
         *
         *     ``version`` is untouched on purpose. The portrait is uploaded from the character list and is
         *     not part of the document the sheet's optimistic concurrency guards; bumping it here would 409
         *     a sheet the same user has open in another tab on its next autosave.
         */
        put: operations["replace_portrait_api_characters__character_id__portrait_put"];
        post?: never;
        /**
         * Delete Portrait
         * @description Removing a portrait a character does not have succeeds — the state asked for is the state
         *     that results, and a card whose remove control raced a reload should not report a failure.
         */
        delete: operations["delete_portrait_api_characters__character_id__portrait_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/derive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derive Endpoint */
        post: operations["derive_endpoint_api_derive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_users__id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Ability
         * @description The six ability scores, used as skill keys and save keys.
         * @enum {string}
         */
        Ability: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
        /**
         * AbilityBlock
         * @description One row of the ability table: the score actually in effect and its modifier.
         */
        AbilityBlock: {
            /**
             * Is Temporary
             * @default false
             */
            is_temporary: boolean;
            /** Modifier */
            modifier: number;
            /** Score */
            score: number;
        };
        /**
         * ArmorRow
         * @description One GEAR slot as stored.
         */
        "ArmorRow-Input": {
            /**
             * Ac Bonus
             * @default 0
             */
            ac_bonus: number;
            /**
             * Check Penalty
             * @default 0
             */
            check_penalty: number;
            /** Id */
            id?: string | null;
            /** Max Dex */
            max_dex?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            slot: components["schemas"]["ArmorSlot"];
            /**
             * Special Properties
             * @default
             */
            special_properties: string;
            /**
             * Speed
             * @default
             */
            speed: string;
            /**
             * Spell Failure
             * @default 0
             */
            spell_failure: number;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Weight
             * @default 0
             */
            weight: number | string;
        };
        /**
         * ArmorRow
         * @description One GEAR slot as stored.
         */
        "ArmorRow-Output": {
            /**
             * Ac Bonus
             * @default 0
             */
            ac_bonus: number;
            /**
             * Check Penalty
             * @default 0
             */
            check_penalty: number;
            /** Id */
            id?: string | null;
            /** Max Dex */
            max_dex?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            slot: components["schemas"]["ArmorSlot"];
            /**
             * Special Properties
             * @default
             */
            special_properties: string;
            /**
             * Speed
             * @default
             */
            speed: string;
            /**
             * Spell Failure
             * @default 0
             */
            spell_failure: number;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Weight
             * @default 0
             */
            weight: string;
        };
        /**
         * ArmorSlot
         * @description The four GEAR slots on page 2 of the sheet.
         *
         *     Only ``armor`` and ``shield`` carry a max-Dex limit and a check penalty on the paper form;
         *     the two protective-item slots contribute an AC bonus and a weight.
         * @enum {string}
         */
        ArmorSlot: "armor" | "shield" | "protective_1" | "protective_2";
        /**
         * AttackRow
         * @description One ATTACK block. ``attack_bonus`` and ``damage`` are typed by the user in phase 1.
         */
        AttackRow: {
            /**
             * Ammunition
             * @default
             */
            ammunition: string;
            /**
             * Attack Bonus
             * @default
             */
            attack_bonus: string;
            /**
             * Critical
             * @default
             */
            critical: string;
            /**
             * Damage
             * @default
             */
            damage: string;
            /**
             * Damage Type
             * @default
             */
            damage_type: string;
            /** Id */
            id?: string | null;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Ordinal
             * @default 0
             */
            ordinal: number;
            /**
             * Range
             * @default
             */
            range: string;
        };
        /** Body_auth_cookie_login_api_auth_login_post */
        Body_auth_cookie_login_api_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_reset_forgot_password_api_auth_forgot_password_post */
        Body_reset_forgot_password_api_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_api_auth_reset_password_post */
        Body_reset_reset_password_api_auth_reset_password_post: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** Body_verify_request_token_api_auth_request_verify_token_post */
        Body_verify_request_token_api_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_api_auth_verify_post */
        Body_verify_verify_api_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * CharacterBody
         * @description Every field on both pages of the paper sheet, including those not yet computed.
         *
         *     Every field has a default, so ``model_dump(exclude_unset=True)`` gives true partial-update
         *     semantics on ``PATCH`` without a parallel all-optional model.
         */
        CharacterBody: {
            /**
             * Ac Deflection
             * @default 0
             */
            ac_deflection: number;
            /**
             * Ac Misc
             * @default 0
             */
            ac_misc: number;
            /**
             * Ac Natural
             * @default 0
             */
            ac_natural: number;
            /**
             * Ac Size
             * @default 0
             */
            ac_size: number;
            /**
             * Age
             * @default
             */
            age: string;
            /**
             * Alignment
             * @default
             */
            alignment: string;
            /** Armor */
            armor?: components["schemas"]["ArmorRow-Input"][];
            /** Attacks */
            attacks?: components["schemas"]["AttackRow"][];
            /**
             * Base Attack Bonus
             * @default 0
             */
            base_attack_bonus: number;
            /**
             * Base Fortitude
             * @default 0
             */
            base_fortitude: number;
            /**
             * Base Reflex
             * @default 0
             */
            base_reflex: number;
            /**
             * Base Will
             * @default 0
             */
            base_will: number;
            /**
             * Body Weight
             * @default
             */
            body_weight: string;
            /**
             * Campaign
             * @default
             */
            campaign: string;
            /**
             * Cha Score
             * @default 10
             */
            cha_score: number;
            /** Cha Temp */
            cha_temp?: number | null;
            /** Class Levels */
            class_levels?: components["schemas"]["ClassLevelRow"][];
            /**
             * Con Score
             * @default 10
             */
            con_score: number;
            /** Con Temp */
            con_temp?: number | null;
            /**
             * Damage Reduction
             * @default
             */
            damage_reduction: string;
            /**
             * Deity
             * @default
             */
            deity: string;
            /**
             * Dex Score
             * @default 10
             */
            dex_score: number;
            /** Dex Temp */
            dex_temp?: number | null;
            /**
             * Experience Points
             * @default 0
             */
            experience_points: number;
            /**
             * Eyes
             * @default
             */
            eyes: string;
            /** Feats */
            feats?: components["schemas"]["NamedReference"][];
            /**
             * Fortitude Magic
             * @default 0
             */
            fortitude_magic: number;
            /**
             * Fortitude Misc
             * @default 0
             */
            fortitude_misc: number;
            /**
             * Fortitude Temporary
             * @default 0
             */
            fortitude_temporary: number;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Grapple Misc
             * @default 0
             */
            grapple_misc: number;
            /**
             * Grapple Size Modifier
             * @default 0
             */
            grapple_size_modifier: number;
            /**
             * Hair
             * @default
             */
            hair: string;
            /**
             * Height
             * @default
             */
            height: string;
            /**
             * Hp Current
             * @default 0
             */
            hp_current: number;
            /**
             * Hp Total
             * @default 0
             */
            hp_total: number;
            /**
             * Initiative Misc
             * @default 0
             */
            initiative_misc: number;
            /**
             * Int Score
             * @default 10
             */
            int_score: number;
            /** Int Temp */
            int_temp?: number | null;
            /** Languages */
            languages?: string[];
            /**
             * Money Cp
             * @default 0
             */
            money_cp: number;
            /**
             * Money Gp
             * @default 0
             */
            money_gp: number;
            /**
             * Money Pp
             * @default 0
             */
            money_pp: number;
            /**
             * Money Sp
             * @default 0
             */
            money_sp: number;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Nonlethal Damage
             * @default 0
             */
            nonlethal_damage: number;
            /**
             * Player Name
             * @default
             */
            player_name: string;
            /** Possessions */
            possessions?: components["schemas"]["PossessionRow-Input"][];
            /**
             * Race
             * @default
             */
            race: string;
            /**
             * Reflex Magic
             * @default 0
             */
            reflex_magic: number;
            /**
             * Reflex Misc
             * @default 0
             */
            reflex_misc: number;
            /**
             * Reflex Temporary
             * @default 0
             */
            reflex_temporary: number;
            /**
             * Saves Conditional Modifiers
             * @default
             */
            saves_conditional_modifiers: string;
            /**
             * Size
             * @default
             */
            size: string;
            /** Skills */
            skills?: components["schemas"]["SkillRow"][];
            /**
             * Skin
             * @default
             */
            skin: string;
            /** Special Abilities */
            special_abilities?: components["schemas"]["NamedReference"][];
            /**
             * Speed
             * @default
             */
            speed: string;
            /**
             * Spell Resistance
             * @default
             */
            spell_resistance: string;
            /** Spells Raw */
            spells_raw?: {
                [key: string]: unknown;
            };
            /**
             * Str Score
             * @default 10
             */
            str_score: number;
            /** Str Temp */
            str_temp?: number | null;
            /**
             * Will Magic
             * @default 0
             */
            will_magic: number;
            /**
             * Will Misc
             * @default 0
             */
            will_misc: number;
            /**
             * Will Temporary
             * @default 0
             */
            will_temporary: number;
            /**
             * Wis Score
             * @default 10
             */
            wis_score: number;
            /** Wis Temp */
            wis_temp?: number | null;
        };
        /**
         * CharacterCreate
         * @description Creating a character asks for a name and nothing else; everything else has a default.
         */
        CharacterCreate: {
            /**
             * Campaign
             * @default
             */
            campaign: string;
            /**
             * Name
             * @default New character
             */
            name: string;
            /**
             * Player Name
             * @default
             */
            player_name: string;
        };
        /**
         * CharacterPatch
         * @description A partial update. ``version`` is the value the client last read; a stale one is a 409.
         */
        CharacterPatch: {
            /**
             * Ac Deflection
             * @default 0
             */
            ac_deflection: number;
            /**
             * Ac Misc
             * @default 0
             */
            ac_misc: number;
            /**
             * Ac Natural
             * @default 0
             */
            ac_natural: number;
            /**
             * Ac Size
             * @default 0
             */
            ac_size: number;
            /**
             * Age
             * @default
             */
            age: string;
            /**
             * Alignment
             * @default
             */
            alignment: string;
            /** Armor */
            armor?: components["schemas"]["ArmorRow-Input"][];
            /** Attacks */
            attacks?: components["schemas"]["AttackRow"][];
            /**
             * Base Attack Bonus
             * @default 0
             */
            base_attack_bonus: number;
            /**
             * Base Fortitude
             * @default 0
             */
            base_fortitude: number;
            /**
             * Base Reflex
             * @default 0
             */
            base_reflex: number;
            /**
             * Base Will
             * @default 0
             */
            base_will: number;
            /**
             * Body Weight
             * @default
             */
            body_weight: string;
            /**
             * Campaign
             * @default
             */
            campaign: string;
            /**
             * Cha Score
             * @default 10
             */
            cha_score: number;
            /** Cha Temp */
            cha_temp?: number | null;
            /** Class Levels */
            class_levels?: components["schemas"]["ClassLevelRow"][];
            /**
             * Con Score
             * @default 10
             */
            con_score: number;
            /** Con Temp */
            con_temp?: number | null;
            /**
             * Damage Reduction
             * @default
             */
            damage_reduction: string;
            /**
             * Deity
             * @default
             */
            deity: string;
            /**
             * Dex Score
             * @default 10
             */
            dex_score: number;
            /** Dex Temp */
            dex_temp?: number | null;
            /**
             * Experience Points
             * @default 0
             */
            experience_points: number;
            /**
             * Eyes
             * @default
             */
            eyes: string;
            /** Feats */
            feats?: components["schemas"]["NamedReference"][];
            /**
             * Fortitude Magic
             * @default 0
             */
            fortitude_magic: number;
            /**
             * Fortitude Misc
             * @default 0
             */
            fortitude_misc: number;
            /**
             * Fortitude Temporary
             * @default 0
             */
            fortitude_temporary: number;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Grapple Misc
             * @default 0
             */
            grapple_misc: number;
            /**
             * Grapple Size Modifier
             * @default 0
             */
            grapple_size_modifier: number;
            /**
             * Hair
             * @default
             */
            hair: string;
            /**
             * Height
             * @default
             */
            height: string;
            /**
             * Hp Current
             * @default 0
             */
            hp_current: number;
            /**
             * Hp Total
             * @default 0
             */
            hp_total: number;
            /**
             * Initiative Misc
             * @default 0
             */
            initiative_misc: number;
            /**
             * Int Score
             * @default 10
             */
            int_score: number;
            /** Int Temp */
            int_temp?: number | null;
            /** Languages */
            languages?: string[];
            /**
             * Money Cp
             * @default 0
             */
            money_cp: number;
            /**
             * Money Gp
             * @default 0
             */
            money_gp: number;
            /**
             * Money Pp
             * @default 0
             */
            money_pp: number;
            /**
             * Money Sp
             * @default 0
             */
            money_sp: number;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Nonlethal Damage
             * @default 0
             */
            nonlethal_damage: number;
            /**
             * Player Name
             * @default
             */
            player_name: string;
            /** Possessions */
            possessions?: components["schemas"]["PossessionRow-Input"][];
            /**
             * Race
             * @default
             */
            race: string;
            /**
             * Reflex Magic
             * @default 0
             */
            reflex_magic: number;
            /**
             * Reflex Misc
             * @default 0
             */
            reflex_misc: number;
            /**
             * Reflex Temporary
             * @default 0
             */
            reflex_temporary: number;
            /**
             * Saves Conditional Modifiers
             * @default
             */
            saves_conditional_modifiers: string;
            /**
             * Size
             * @default
             */
            size: string;
            /** Skills */
            skills?: components["schemas"]["SkillRow"][];
            /**
             * Skin
             * @default
             */
            skin: string;
            /** Special Abilities */
            special_abilities?: components["schemas"]["NamedReference"][];
            /**
             * Speed
             * @default
             */
            speed: string;
            /**
             * Spell Resistance
             * @default
             */
            spell_resistance: string;
            /** Spells Raw */
            spells_raw?: {
                [key: string]: unknown;
            };
            /**
             * Str Score
             * @default 10
             */
            str_score: number;
            /** Str Temp */
            str_temp?: number | null;
            /** Version */
            version: number;
            /**
             * Will Magic
             * @default 0
             */
            will_magic: number;
            /**
             * Will Misc
             * @default 0
             */
            will_misc: number;
            /**
             * Will Temporary
             * @default 0
             */
            will_temporary: number;
            /**
             * Wis Score
             * @default 10
             */
            wis_score: number;
            /** Wis Temp */
            wis_temp?: number | null;
        };
        /**
         * CharacterPortraitRead
         * @description What an upload or a removal answers with.
         *
         *     Only the timestamp, because that is the whole of what the caller does not already know: it is
         *     what the card hangs on the image URL so the browser fetches the new bytes rather than the ones
         *     it cached a moment ago. Null after a removal.
         */
        CharacterPortraitRead: {
            /** Portrait Updated At */
            portrait_updated_at?: string | null;
        };
        /** CharacterRead */
        CharacterRead: {
            /**
             * Ac Deflection
             * @default 0
             */
            ac_deflection: number;
            /**
             * Ac Misc
             * @default 0
             */
            ac_misc: number;
            /**
             * Ac Natural
             * @default 0
             */
            ac_natural: number;
            /**
             * Ac Size
             * @default 0
             */
            ac_size: number;
            /**
             * Age
             * @default
             */
            age: string;
            /**
             * Alignment
             * @default
             */
            alignment: string;
            /** Armor */
            armor?: components["schemas"]["ArmorRow-Output"][];
            /** Attacks */
            attacks?: components["schemas"]["AttackRow"][];
            /**
             * Base Attack Bonus
             * @default 0
             */
            base_attack_bonus: number;
            /**
             * Base Fortitude
             * @default 0
             */
            base_fortitude: number;
            /**
             * Base Reflex
             * @default 0
             */
            base_reflex: number;
            /**
             * Base Will
             * @default 0
             */
            base_will: number;
            /**
             * Body Weight
             * @default
             */
            body_weight: string;
            /**
             * Campaign
             * @default
             */
            campaign: string;
            /**
             * Cha Score
             * @default 10
             */
            cha_score: number;
            /** Cha Temp */
            cha_temp?: number | null;
            /** Class Levels */
            class_levels?: components["schemas"]["ClassLevelRow"][];
            /**
             * Con Score
             * @default 10
             */
            con_score: number;
            /** Con Temp */
            con_temp?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Damage Reduction
             * @default
             */
            damage_reduction: string;
            /**
             * Deity
             * @default
             */
            deity: string;
            /**
             * Dex Score
             * @default 10
             */
            dex_score: number;
            /** Dex Temp */
            dex_temp?: number | null;
            /**
             * Experience Points
             * @default 0
             */
            experience_points: number;
            /**
             * Eyes
             * @default
             */
            eyes: string;
            /** Feats */
            feats?: components["schemas"]["NamedReference"][];
            /**
             * Fortitude Magic
             * @default 0
             */
            fortitude_magic: number;
            /**
             * Fortitude Misc
             * @default 0
             */
            fortitude_misc: number;
            /**
             * Fortitude Temporary
             * @default 0
             */
            fortitude_temporary: number;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Grapple Misc
             * @default 0
             */
            grapple_misc: number;
            /**
             * Grapple Size Modifier
             * @default 0
             */
            grapple_size_modifier: number;
            /**
             * Hair
             * @default
             */
            hair: string;
            /**
             * Height
             * @default
             */
            height: string;
            /**
             * Hp Current
             * @default 0
             */
            hp_current: number;
            /**
             * Hp Total
             * @default 0
             */
            hp_total: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Initiative Misc
             * @default 0
             */
            initiative_misc: number;
            /**
             * Int Score
             * @default 10
             */
            int_score: number;
            /** Int Temp */
            int_temp?: number | null;
            /** Languages */
            languages?: string[];
            /**
             * Money Cp
             * @default 0
             */
            money_cp: number;
            /**
             * Money Gp
             * @default 0
             */
            money_gp: number;
            /**
             * Money Pp
             * @default 0
             */
            money_pp: number;
            /**
             * Money Sp
             * @default 0
             */
            money_sp: number;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Nonlethal Damage
             * @default 0
             */
            nonlethal_damage: number;
            /**
             * Player Name
             * @default
             */
            player_name: string;
            /** Possessions */
            possessions?: components["schemas"]["PossessionRow-Output"][];
            /**
             * Race
             * @default
             */
            race: string;
            /**
             * Reflex Magic
             * @default 0
             */
            reflex_magic: number;
            /**
             * Reflex Misc
             * @default 0
             */
            reflex_misc: number;
            /**
             * Reflex Temporary
             * @default 0
             */
            reflex_temporary: number;
            /**
             * Saves Conditional Modifiers
             * @default
             */
            saves_conditional_modifiers: string;
            /**
             * Size
             * @default
             */
            size: string;
            /** Skills */
            skills?: components["schemas"]["SkillRow"][];
            /**
             * Skin
             * @default
             */
            skin: string;
            /** Special Abilities */
            special_abilities?: components["schemas"]["NamedReference"][];
            /**
             * Speed
             * @default
             */
            speed: string;
            /**
             * Spell Resistance
             * @default
             */
            spell_resistance: string;
            /** Spells Raw */
            spells_raw?: {
                [key: string]: unknown;
            };
            /**
             * Str Score
             * @default 10
             */
            str_score: number;
            /** Str Temp */
            str_temp?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /**
             * Will Magic
             * @default 0
             */
            will_magic: number;
            /**
             * Will Misc
             * @default 0
             */
            will_misc: number;
            /**
             * Will Temporary
             * @default 0
             */
            will_temporary: number;
            /**
             * Wis Score
             * @default 10
             */
            wis_score: number;
            /** Wis Temp */
            wis_temp?: number | null;
        };
        /**
         * CharacterSummary
         * @description A row of the character list. Deliberately narrow — the list does not derive anything.
         */
        CharacterSummary: {
            /** Campaign */
            campaign: string;
            /** Class Levels */
            class_levels?: components["schemas"]["ClassLevelRow"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Player Name */
            player_name: string;
            /** Portrait Updated At */
            portrait_updated_at?: string | null;
            /** Race */
            race: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * CharacterWithDerived
         * @description What ``GET`` and ``PATCH`` of a single character return.
         */
        CharacterWithDerived: {
            character: components["schemas"]["CharacterRead"];
            derived: components["schemas"]["DerivedSheet"];
            /** Portrait Updated At */
            portrait_updated_at?: string | null;
        };
        /** ClassLevelRow */
        ClassLevelRow: {
            /**
             * Class Name
             * @default
             */
            class_name: string;
            /** Id */
            id?: string | null;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Ordinal
             * @default 0
             */
            ordinal: number;
        };
        /**
         * DerivedAbilities
         * @description The six ability rows.
         *
         *     Named fields rather than a dictionary keyed by ``Ability``: a mapping schema generates a
         *     TypeScript index signature, and the frontend would lose the guarantee that every ability is
         *     present. Indexing by ``Ability`` still works for the engine's own use.
         */
        DerivedAbilities: {
            charisma: components["schemas"]["AbilityBlock"];
            constitution: components["schemas"]["AbilityBlock"];
            dexterity: components["schemas"]["AbilityBlock"];
            intelligence: components["schemas"]["AbilityBlock"];
            strength: components["schemas"]["AbilityBlock"];
            wisdom: components["schemas"]["AbilityBlock"];
        };
        /** DerivedArmorClass */
        DerivedArmorClass: {
            /** Armor Bonus */
            armor_bonus: number;
            /** Deflection */
            deflection: number;
            /** Effective Dex Bonus */
            effective_dex_bonus: number;
            /** Flat Footed */
            flat_footed: number;
            /** Misc */
            misc: number;
            /** Natural Armor */
            natural_armor: number;
            /** Shield Bonus */
            shield_bonus: number;
            /** Size Modifier */
            size_modifier: number;
            /** Total */
            total: number;
            /** Touch */
            touch: number;
        };
        /** DerivedEncumbrance */
        DerivedEncumbrance: {
            /** Carried Weight */
            carried_weight: string;
            category: components["schemas"]["LoadCategory"];
            /** Heavy Load */
            heavy_load: number;
            /** Lift Off Ground */
            lift_off_ground: number;
            /** Lift Over Head */
            lift_over_head: number;
            /** Light Load */
            light_load: number;
            /** Medium Load */
            medium_load: number;
            /** Push Or Drag */
            push_or_drag: number;
        };
        /** DerivedSave */
        DerivedSave: {
            /** Ability Modifier */
            ability_modifier: number;
            /** Base */
            base: number;
            /** Magic */
            magic: number;
            /** Misc */
            misc: number;
            /** Temporary */
            temporary: number;
            /** Total */
            total: number;
        };
        /**
         * DerivedSaves
         * @description The three saving-throw rows, named for the same reason the abilities are.
         */
        DerivedSaves: {
            fortitude: components["schemas"]["DerivedSave"];
            reflex: components["schemas"]["DerivedSave"];
            will: components["schemas"]["DerivedSave"];
        };
        /**
         * DerivedSheet
         * @description Every number the paper sheet asks you to work out by hand.
         */
        DerivedSheet: {
            abilities: components["schemas"]["DerivedAbilities"];
            /** Armor Check Penalty */
            armor_check_penalty: number;
            armor_class: components["schemas"]["DerivedArmorClass"];
            /** Character Level */
            character_level: number;
            encumbrance: components["schemas"]["DerivedEncumbrance"];
            /** Grapple Modifier */
            grapple_modifier: number;
            /** Initiative */
            initiative: number;
            saves: components["schemas"]["DerivedSaves"];
            /** Skills */
            skills: components["schemas"]["DerivedSkill"][];
            /** Total Ranks */
            total_ranks: number;
            /** Warnings */
            warnings?: components["schemas"]["RuleWarning"][];
        };
        /** DerivedSkill */
        DerivedSkill: {
            /** Ability Modifier */
            ability_modifier: number;
            /** Armor Check Penalty */
            armor_check_penalty: number;
            /** Is Class Skill */
            is_class_skill: boolean;
            /** Key */
            key: string | null;
            key_ability: components["schemas"]["Ability"];
            /** Max Ranks */
            max_ranks: number;
            /** Misc Modifier */
            misc_modifier: number;
            /** Name */
            name: string;
            /** Ranks */
            ranks: number;
            /** Skill Id */
            skill_id: number | null;
            /** Specialization */
            specialization: string | null;
            /** Total */
            total: number;
            /** Usable Untrained */
            usable_untrained: boolean;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoadCategory
         * @enum {string}
         */
        LoadCategory: "light" | "medium" | "heavy" | "overloaded";
        /**
         * NamedReference
         * @description A feat or special ability, with the **PG.** column the paper sheet prints beside it.
         */
        NamedReference: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Page
             * @default
             */
            page: string;
        };
        /**
         * PossessionRow
         * @description An OTHER POSSESSIONS row. Stored in JSONB because it is only ever summed.
         */
        "PossessionRow-Input": {
            /**
             * Item
             * @default
             */
            item: string;
            /**
             * Page
             * @default
             */
            page: string;
            /**
             * Weight
             * @default 0
             */
            weight: number | string;
        };
        /**
         * PossessionRow
         * @description An OTHER POSSESSIONS row. Stored in JSONB because it is only ever summed.
         */
        "PossessionRow-Output": {
            /**
             * Item
             * @default
             */
            item: string;
            /**
             * Page
             * @default
             */
            page: string;
            /**
             * Weight
             * @default 0
             */
            weight: string;
        };
        /**
         * Problem
         * @description RFC 7807 ``application/problem+json``.
         */
        Problem: {
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * RuleWarning
         * @description A rules violation that the application reports rather than refuses.
         *
         *     House rules and homebrew are normal play, so nothing here is an error. Named ``RuleWarning``
         *     rather than ``Warning`` so it does not shadow the builtin.
         *
         *     ``message`` is English and stays that way: the engine has no locale and is not going to grow
         *     one. ``params`` carries the same facts as **tokens** — a skill identifier, a number, a
         *     ``kind`` of ``"class"`` or ``"cross_class"`` — so a client that speaks another language can
         *     build the sentence itself rather than splicing a translation around English fragments. Values
         *     are strings because a warning's parameters differ per code and end up in text either way.
         */
        RuleWarning: {
            code: components["schemas"]["WarningCode"];
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
        };
        /** SkillDefinitionRead */
        SkillDefinitionRead: {
            /** Acp Double */
            acp_double: boolean;
            /** Armor Check Penalty */
            armor_check_penalty: boolean;
            /** Id */
            id: number;
            key_ability: components["schemas"]["Ability"];
            /** Name */
            name: string;
            /** Name Fr */
            name_fr?: string | null;
            /** Sheet Rows */
            sheet_rows: number;
            /** Takes Specialization */
            takes_specialization: boolean;
            /** Usable Untrained */
            usable_untrained: boolean;
        };
        /**
         * SkillRow
         * @description One SKILLS row as stored. Exactly one of ``skill_id`` and ``custom_name`` is set.
         */
        SkillRow: {
            custom_key_ability?: components["schemas"]["Ability"] | null;
            /** Custom Name */
            custom_name?: string | null;
            /** Id */
            id?: string | null;
            /**
             * Is Class Skill
             * @default false
             */
            is_class_skill: boolean;
            /**
             * Misc Modifier
             * @default 0
             */
            misc_modifier: number;
            /**
             * Ordinal
             * @default 0
             */
            ordinal: number;
            /**
             * Ranks
             * @default 0
             */
            ranks: number;
            /** Skill Id */
            skill_id?: number | null;
            /** Specialization */
            specialization?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WarningCode
         * @enum {string}
         */
        WarningCode: "ranks_over_maximum" | "dex_bonus_exceeds_max_dex" | "overloaded" | "unknown_skill";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reset_forgot_password_api_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_api_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_api_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_api_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_api_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_api_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_api_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_api_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_api_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterSummary"][];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_character_api_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterWithDerived"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    read_character_api_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterWithDerived"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_character_api_characters__character_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_character_api_characters__character_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterWithDerived"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    read_portrait_api_characters__character_id__portrait_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The portrait, in the media type it was uploaded as. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/gif": unknown;
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description No such character. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    replace_portrait_api_characters__character_id__portrait_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterPortraitRead"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_portrait_api_characters__character_id__portrait_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterPortraitRead"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    derive_endpoint_api_derive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedSheet"];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDefinitionRead"][];
                };
            };
            /** @description RFC 7807 problem document */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    users_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
