"""initial schema

Revision ID: 10fd970bc61d
Revises:
Create Date: 2026-07-25 20:12:55.413201
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "10fd970bc61d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("key_ability", sa.String(length=3), nullable=False),
        sa.Column("armor_check_penalty", sa.Boolean(), nullable=False),
        sa.Column("acp_double", sa.Boolean(), nullable=False),
        sa.Column("usable_untrained", sa.Boolean(), nullable=False),
        sa.Column("takes_specialization", sa.Boolean(), nullable=False),
        sa.Column("sheet_rows", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "key_ability IN ('STR','DEX','CON','INT','WIS','CHA')", name="ck_skills_key_ability"
        ),
        sa.CheckConstraint("sheet_rows >= 1", name="ck_skills_sheet_rows_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "access_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_access_tokens_created_at"), "access_tokens", ["created_at"], unique=False
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("player_name", sa.String(length=120), nullable=False),
        sa.Column("race", sa.String(length=60), nullable=False),
        sa.Column("alignment", sa.String(length=30), nullable=False),
        sa.Column("deity", sa.String(length=60), nullable=False),
        sa.Column("size", sa.String(length=20), nullable=False),
        sa.Column("age", sa.String(length=20), nullable=False),
        sa.Column("gender", sa.String(length=30), nullable=False),
        sa.Column("height", sa.String(length=20), nullable=False),
        sa.Column("body_weight", sa.String(length=20), nullable=False),
        sa.Column("eyes", sa.String(length=30), nullable=False),
        sa.Column("hair", sa.String(length=30), nullable=False),
        sa.Column("skin", sa.String(length=30), nullable=False),
        sa.Column("campaign", sa.String(length=120), nullable=False),
        sa.Column("experience_points", sa.Integer(), nullable=False),
        sa.Column("str_score", sa.Integer(), nullable=False),
        sa.Column("dex_score", sa.Integer(), nullable=False),
        sa.Column("con_score", sa.Integer(), nullable=False),
        sa.Column("int_score", sa.Integer(), nullable=False),
        sa.Column("wis_score", sa.Integer(), nullable=False),
        sa.Column("cha_score", sa.Integer(), nullable=False),
        sa.Column("str_temp", sa.Integer(), nullable=True),
        sa.Column("dex_temp", sa.Integer(), nullable=True),
        sa.Column("con_temp", sa.Integer(), nullable=True),
        sa.Column("int_temp", sa.Integer(), nullable=True),
        sa.Column("wis_temp", sa.Integer(), nullable=True),
        sa.Column("cha_temp", sa.Integer(), nullable=True),
        sa.Column("hp_total", sa.Integer(), nullable=False),
        sa.Column("hp_current", sa.Integer(), nullable=False),
        sa.Column("nonlethal_damage", sa.Integer(), nullable=False),
        sa.Column("damage_reduction", sa.String(length=60), nullable=False),
        sa.Column("speed", sa.String(length=60), nullable=False),
        sa.Column("spell_resistance", sa.String(length=60), nullable=False),
        sa.Column("base_attack_bonus", sa.Integer(), nullable=False),
        sa.Column("grapple_misc", sa.Integer(), nullable=False),
        sa.Column("grapple_size_modifier", sa.Integer(), nullable=False),
        sa.Column("initiative_misc", sa.Integer(), nullable=False),
        sa.Column("base_fortitude", sa.Integer(), nullable=False),
        sa.Column("fortitude_magic", sa.Integer(), nullable=False),
        sa.Column("fortitude_misc", sa.Integer(), nullable=False),
        sa.Column("fortitude_temporary", sa.Integer(), nullable=False),
        sa.Column("base_reflex", sa.Integer(), nullable=False),
        sa.Column("reflex_magic", sa.Integer(), nullable=False),
        sa.Column("reflex_misc", sa.Integer(), nullable=False),
        sa.Column("reflex_temporary", sa.Integer(), nullable=False),
        sa.Column("base_will", sa.Integer(), nullable=False),
        sa.Column("will_magic", sa.Integer(), nullable=False),
        sa.Column("will_misc", sa.Integer(), nullable=False),
        sa.Column("will_temporary", sa.Integer(), nullable=False),
        sa.Column("saves_conditional_modifiers", sa.Text(), nullable=False),
        sa.Column("ac_natural", sa.Integer(), nullable=False),
        sa.Column("ac_deflection", sa.Integer(), nullable=False),
        sa.Column("ac_size", sa.Integer(), nullable=False),
        sa.Column("ac_misc", sa.Integer(), nullable=False),
        sa.Column("money_cp", sa.Integer(), nullable=False),
        sa.Column("money_sp", sa.Integer(), nullable=False),
        sa.Column("money_gp", sa.Integer(), nullable=False),
        sa.Column("money_pp", sa.Integer(), nullable=False),
        sa.Column(
            "possessions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "feats", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "special_abilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "languages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "spells_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_owner_id"), "characters", ["owner_id"], unique=False)
    op.create_table(
        "character_armor",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("ac_bonus", sa.Integer(), nullable=False),
        sa.Column("max_dex", sa.Integer(), nullable=True),
        sa.Column("check_penalty", sa.Integer(), nullable=False),
        sa.Column("spell_failure", sa.Integer(), nullable=False),
        sa.Column("speed", sa.String(length=30), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("special_properties", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "slot IN ('armor','shield','protective_1','protective_2')",
            name="ck_character_armor_slot",
        ),
        sa.CheckConstraint(
            "check_penalty <= 0", name="ck_character_armor_check_penalty_non_positive"
        ),
        sa.CheckConstraint("weight >= 0", name="ck_character_armor_weight_non_negative"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "slot", name="uq_character_armor_slot"),
    )
    op.create_table(
        "character_attacks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("attack_bonus", sa.String(length=60), nullable=False),
        sa.Column("damage", sa.String(length=60), nullable=False),
        sa.Column("critical", sa.String(length=40), nullable=False),
        sa.Column("range", sa.String(length=40), nullable=False),
        sa.Column("damage_type", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("ammunition", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_character_attacks_character_id", "character_attacks", ["character_id"], unique=False
    )
    op.create_table(
        "character_class_levels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=60), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.CheckConstraint("level >= 1", name="ck_class_levels_level_positive"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_character_class_levels_character_id",
        "character_class_levels",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "character_skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.Column("custom_name", sa.String(length=64), nullable=True),
        sa.Column("custom_key_ability", sa.String(length=3), nullable=True),
        sa.Column("specialization", sa.String(length=64), nullable=True),
        sa.Column("ranks", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("misc_modifier", sa.Integer(), nullable=False),
        sa.Column("is_class_skill", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(skill_id IS NULL) <> (custom_name IS NULL)",
            name="ck_character_skills_exactly_one_identity",
        ),
        sa.CheckConstraint("ranks >= 0", name="ck_character_skills_ranks_non_negative"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_character_skills_character_id", "character_skills", ["character_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_character_skills_character_id", table_name="character_skills")
    op.drop_table("character_skills")
    op.drop_index("ix_character_class_levels_character_id", table_name="character_class_levels")
    op.drop_table("character_class_levels")
    op.drop_index("ix_character_attacks_character_id", table_name="character_attacks")
    op.drop_table("character_attacks")
    op.drop_table("character_armor")
    op.drop_index(op.f("ix_characters_owner_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_access_tokens_created_at"), table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("skills")
    # ### end Alembic commands ###
