/** Fixtures for the component tests: a small character and the sheet the API would derive. */
import type {
  CharacterRead,
  DerivedSheet,
  DerivedSkill,
  SkillDefinition,
} from "../api/types";

export const DEFINITIONS: SkillDefinition[] = [
  {
    id: 16,
    name: "Hide",
    name_fr: "Discrétion",
    key_ability: "DEX",
    armor_check_penalty: true,
    acp_double: false,
    usable_untrained: true,
    takes_specialization: false,
    sheet_rows: 1,
  },
  {
    id: 32,
    name: "Swim",
    name_fr: "Natation",
    key_ability: "STR",
    armor_check_penalty: true,
    acp_double: true,
    usable_untrained: true,
    takes_specialization: false,
    sheet_rows: 1,
  },
  {
    id: 19,
    name: "Knowledge",
    name_fr: "Connaissances",
    key_ability: "INT",
    armor_check_penalty: false,
    acp_double: false,
    usable_untrained: false,
    takes_specialization: true,
    sheet_rows: 5,
  },
];

function block(score: number, modifier: number, is_temporary = false) {
  return { score, modifier, is_temporary };
}

function save(base: number, ability_modifier: number, total: number) {
  return { base, ability_modifier, magic: 0, misc: 0, temporary: 0, total };
}

export function derivedSkill(overrides: Partial<DerivedSkill> = {}): DerivedSkill {
  return {
    key: "row-0",
    skill_id: 16,
    name: "Hide",
    specialization: null,
    key_ability: "DEX",
    is_class_skill: false,
    usable_untrained: true,
    ranks: 0,
    ability_modifier: 2,
    misc_modifier: 0,
    armor_check_penalty: 0,
    total: 2,
    max_ranks: 3,
    ...overrides,
  };
}

export function derivedSheet(overrides: Partial<DerivedSheet> = {}): DerivedSheet {
  return {
    character_level: 1,
    abilities: {
      strength: block(13, 1),
      dexterity: block(14, 2),
      constitution: block(16, 3, true),
      intelligence: block(12, 1),
      wisdom: block(10, 0),
      charisma: block(8, -1),
    },
    armor_class: {
      armor_bonus: 0,
      shield_bonus: 0,
      effective_dex_bonus: 2,
      size_modifier: 0,
      natural_armor: 0,
      deflection: 0,
      misc: 0,
      total: 12,
      touch: 12,
      flat_footed: 10,
    },
    initiative: 2,
    grapple_modifier: 1,
    armor_check_penalty: 0,
    saves: { fortitude: save(2, 3, 5), reflex: save(0, 2, 2), will: save(2, 0, 2) },
    skills: [derivedSkill()],
    // A flat 0, deliberately not summed from `skills` above: a fixture that recomputed it would be
    // a second implementation of the engine's sum, and would agree with itself while disagreeing
    // with the engine. A test that asserts on the count passes the count it expects.
    total_ranks: 0,
    encumbrance: {
      carried_weight: "0",
      light_load: 50,
      medium_load: 100,
      heavy_load: 150,
      category: "light",
      lift_over_head: 150,
      lift_off_ground: 300,
      push_or_drag: 750,
    },
    warnings: [],
    ...overrides,
  };
}

export function character(overrides: Partial<CharacterRead> = {}): CharacterRead {
  return {
    id: "11111111-2222-3333-4444-555555555555",
    version: 1,
    created_at: "2026-07-25T12:00:00Z",
    updated_at: "2026-07-25T12:00:00Z",
    name: "Bramwell",
    player_name: "",
    race: "Gnome",
    alignment: "",
    deity: "",
    size: "Small",
    age: "",
    gender: "",
    height: "",
    body_weight: "42",
    eyes: "",
    hair: "",
    skin: "",
    campaign: "",
    experience_points: 0,
    str_score: 13,
    dex_score: 14,
    con_score: 14,
    int_score: 12,
    wis_score: 10,
    cha_score: 8,
    str_temp: null,
    dex_temp: null,
    con_temp: 16,
    int_temp: null,
    wis_temp: null,
    cha_temp: null,
    hp_total: 0,
    hp_current: 0,
    nonlethal_damage: 0,
    damage_reduction: "",
    speed: "",
    spell_resistance: "",
    base_attack_bonus: 0,
    grapple_misc: 0,
    grapple_size_modifier: -4,
    initiative_misc: 0,
    base_fortitude: 2,
    fortitude_magic: 0,
    fortitude_misc: 0,
    fortitude_temporary: 0,
    base_reflex: 0,
    reflex_magic: 0,
    reflex_misc: 0,
    reflex_temporary: 0,
    base_will: 2,
    will_magic: 0,
    will_misc: 0,
    will_temporary: 0,
    saves_conditional_modifiers: "",
    ac_natural: 0,
    ac_deflection: 0,
    ac_size: 1,
    ac_misc: 0,
    money_cp: 0,
    money_sp: 0,
    money_gp: 0,
    money_pp: 0,
    possessions: [],
    feats: [],
    special_abilities: [],
    languages: [],
    spells_raw: {},
    class_levels: [{ id: null, ordinal: 0, class_name: "Rogue", level: 1 }],
    skills: [
      {
        id: "aaaaaaaa-0000-0000-0000-000000000001",
        ordinal: 0,
        skill_id: 16,
        custom_name: null,
        custom_key_ability: null,
        specialization: null,
        ranks: 0,
        misc_modifier: 0,
        is_class_skill: false,
      },
    ],
    armor: [],
    attacks: [],
    ...overrides,
  };
}
